// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2025. 5. 21. 오전 12:33:58
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/ssosso/Desktop/ICNA0520/ICNA_0520_save_2/icna_frontend_full/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ssosso/Desktop/ICNA0520/ICNA_0520_save_2/icna_frontend_full/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ssosso/Desktop/ICNA0520/ICNA_0520_save_2/icna_frontend_full/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ssosso/Desktop/ICNA0520/ICNA_0520_save_2/icna_frontend_full/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ssosso/Desktop/ICNA0520/ICNA_0520_save_2/icna_frontend_full/plugins/**/*.{js,ts,mjs}","C:/Users/ssosso/Desktop/ICNA0520/ICNA_0520_save_2/icna_frontend_full/composables/**/*.{js,ts,mjs}","C:/Users/ssosso/Desktop/ICNA0520/ICNA_0520_save_2/icna_frontend_full/utils/**/*.{js,ts,mjs}","C:/Users/ssosso/Desktop/ICNA0520/ICNA_0520_save_2/icna_frontend_full/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ssosso/Desktop/ICNA0520/ICNA_0520_save_2/icna_frontend_full/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ssosso/Desktop/ICNA0520/ICNA_0520_save_2/icna_frontend_full/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ssosso/Desktop/ICNA0520/ICNA_0520_save_2/icna_frontend_full/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;